CREATE TABLE [dbo].[Admin]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[Username] NVARCHAR(50) NOT NULL UNIQUE,
	[Password] NVARCHAR(255) NOT NULL,
	[Email] NVARCHAR(255) NOT NULL UNIQUE,
	[Designation] NVARCHAR(100) NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
	[UpdatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
	[IsActive] BIT NOT NULL DEFAULT 1
)
