CREATE TABLE [dbo].[InventoryDetails]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[ProductId] UNIQUEIDENTIFIER NOT NULL,
	[StockQuantity] INT NOT NULL DEFAULT(0),
	[ReorderLevel] INT NOT NULL DEFAULT(10),
	[LastRestockedAt] DATETIME NULL,
	[IsActive] BIT NOT NULL DEFAULT(1),
	[CreatedAt] DATETIME NOT NULL DEFAULT(GETDATE()),
	[UpdatedAt] DATETIME NULL DEFAULT(GETDATE()),
	FOREIGN KEY ([ProductId]) REFERENCES [dbo].[ProductDetails]([ProductId]) ON DELETE CASCADE ON UPDATE CASCADE
)
