CREATE TABLE [dbo].[OrderStatus]
(
	[StatusId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[StatusName] NVARCHAR(50) NOT NULL UNIQUE,
	[CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
	[UpdatedAt] DATETIME NOT NULL DEFAULT GETDATE()
)
