CREATE TABLE [dbo].[PaymentType]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(100) NOT NULL UNIQUE,
	[IsActive] BIT NOT NULL DEFAULT(1),
	[CreatedAt] DATETIME NOT NULL DEFAULT(GETDATE()),
	[UpdatedAt] DATETIME NULL DEFAULT(GETDATE())
)
