CREATE TABLE [dbo].[ProductDetails]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[ProductId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[CategoryCode] UNIQUEIDENTIFIER NOT NULL,
	[ProductName] NVARCHAR(MAX) NOT NULL,
	[Description] NVARCHAR(MAX) NULL,
	[Price] DECIMAL(18, 2) NOT NULL,
	[IsActive] BIT NOT NULL DEFAULT(1),
	[CreatedAt] DATETIME NOT NULL DEFAULT(GETDATE()),
	[UpdatedAt] DATETIME NULL DEFAULT(GETDATE()),
	FOREIGN KEY ([CategoryCode]) REFERENCES [dbo].[ProductCategory]([CategoryCode]) ON DELETE CASCADE ON UPDATE CASCADE
)
