CREATE TABLE [dbo].[ProductCategory]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[CategoryCode] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL UNIQUE,
	[CategoryType] NVARCHAR(255) NOT NULL,
	[IsActive] BIT NOT NULL DEFAULT(1),
	[CreatedAt] DATETIME NOT NULL DEFAULT(GETDATE()),
	[UpdatedAt] DATETIME NULL DEFAULT(GETDATE())
)
